name: propcheck
version: 0.3.3
author: Paul Brauner <polux@google.com>
description: A library for exhaustive and randomized testing of Dart properties
homepage: https://github.com/polux/propcheck
documentation: http://goo.gl/QHAamB
environment:
  sdk: '>=0.4.7'
dependencies:
  enumerators: '>=0.4.0 <0.5.0'
dev_dependencies:
  unittest: any
