name: propcheck
author: Paul Brauner <polux@google.com>
version: 0.5.1
homepage: https://github.com/polux/propcheck
description: A library for exhaustive and randomized testing of Dart properties
documentation: http://www.dartdocs.org/documentation/propcheck/0.5.0/index.html#propcheck
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  enumerators: '>=0.5.5 <0.6.0'
  vacuum_persistent: any
dev_dependencies:
  collection: '>=0.9.3 <1.2.0'
  unittest: '>=0.9.0 <0.12.0'
